config/routes.rb
Rails.application.routes.draw do

  root "events#index"

  # use a ruby block here to nest
  resources :events do
    resources :registrations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates :name, :location, presence: true
    validates :description, length: {minimum:25}
    validates :price, numericality: { greater_than_or_equal_to: 0 }
    validates :capacity, numericality: { only_integer: true, greater_than: 0 }
    validates :image_file_name, allow_blank: true, format: {
        with:    /\w+\.(gif|jpg|png)\z/i,
        message: "must reference a GIF, JPG, or PNG image"
    }
    
    # destroy each child when parent object is destroyed.
    has_many :registrations, dependent: :destroy

    # if an event is free it is business logic, so goes in model
    def free?
        price.blank? || price.zero? 
    end    

    def self.upcoming
        where("starts_at >= ?", Time.now).order("starts_at") 
    end   
end

app/models/registration.rb
class Registration < ApplicationRecord
  validates :name, presence: true
  validates :email, format: { with: /(\S+)@(\S+)/ }

  HOW_HEARD_OPTIONS = [
    'Newsletter',
    'Blog Post',
    'Twitter',
    'Web Search',
    'Friend/Coworker',
    'Other'
  ]

  validates :how_heard,
            inclusion: { in: HOW_HEARD_OPTIONS }

  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    def index
        # was  @events = Event.all
        @events = Event.upcoming
    end

    def show
        @event = Event.find(params[:id])
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        @event = Event.find(params[:id])
        if @event.update(event_params)
            redirect_to @event, notice:"Event successfully updated"
        else
            render :edit
        end    
    end

    def new
        @event = Event.new
    end

    def create
        @event = Event.new(event_params)
        if @event.save
            redirect_to @event
        else
            render :new
        end
    end

    def destroy
        @event = Event.find(params[:id])
        @event.destroy
        redirect_to events_url
    end

    private

    def event_params
        event_params = params.require(:event).permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def index
        @event = Event.find(params[:event_id])
        @registrations = @event.registrations
    end

    def new
        @event = Event.find(params[:event_id])
        @registration = @event.registrations.new
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
    def format_price(event)

        if event.free?
            #"<strong>Free!</strong>".html_safe
            content_tag(:strong, "Free!")
        else
            number_to_currency(event.price)
        end
    end    

    def image_for(event)
        if event.image_file_name.blank?
            image_tag 'placeholder.png'
        else
            image_tag event.image_file_name
        end
    end    
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f|%>
    <%= render 'shared/errors' %>
<p>
    <%= f.label :name %> <br>
    <%= f.text_field :name, autofocus: true %>
</p>
<p>
    <%= f.label :description %> <br>
    <%= f.text_area :description, cols:40, rows: 7 %>
</p>
<p>
    <%= f.label :location %> <br>
    <%= f.text_field :location %>
</p>
<p>
    <%= f.label :price %> <br>
    <%= f.number_field :price %>
</p>
<p>
    <%= f.label :starts_at %> <br>
    <%= f.datetime_select :starts_at %>
</p>
<p>
    <%= f.label :image_file_name %> <br>
    <%= f.text_field :image_file_name, size: 30,
        placeholder: "GIF, JPG, or PNG file name" %>
</p>
<p>
    <%= f.label :capacity %> <br>
    <%= f.number_field :capacity %>
</p>
<p>
    <%= f.submit %> | 
    <%= link_to "Cancel", events_path %> |
</p>
<% end %>

app/views/events/edit.html.erb
<div class="container">
    <h1>Editing <%= @event.name %></h1>

    <%= render "form" %>
    
</div>    

app/views/events/index.html.erb
<%= render 'layouts/jumbotron' %>
<% @events.each do |event| %>

    <article>
        <div class="container">
            <div class="card my-5" style="width: 20rem;">
                <div class="card-header">
                    <h3 class="card-title"><%= link_to(event.name, event) %></h3>
                    <h4 class="card-title"><%= pluralize(event.capacity, 'seat') %></h4>
                </div>
                <img class="card-img-top"><%= image_for(event)%>                
                <div class="card-body">
                    <p class="card-text"><%= truncate(event.description, length: 35, separator: ' ') %></p>
                    <p class="card-text">When:<%= event.starts_at %></p>
                    <p class="card-text">Where:<%= event.location %>.</p>
                    <p class="card-text">Price: <%= format_price(event) %>.</p>
                </div>
            </div>
        </div>

    </article>        
<% end %>

app/views/events/new.html.erb
<div class="container">
    <h1>Add New Event <%# @event.name %></h1>

    <%= render "form" %>
</div>    

app/views/events/show.html.erb
<div class="container">
    <div class="card my-5">
        <img class="card-img-top"><%= image_for(@event)%>
        <div class="card-body">
            <h3 class="card-title"><%=@event.name %></h3>
            <p class="card-text">When: <%= @event.location %></p>
            <p class="card-text">Price: <%= format_price(@event) %></p>
            <p class="card-text">Capacity: <%= pluralize(@event.capacity, 'seat') %></p>
            <p class="card-text"><%= @event.description %></p>
            <%= link_to "Edit", edit_event_path(@event), class: "btn btn-warning" %>
            <%= link_to "Delete", event_path(@event), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
        </div>
        <div class="card-footer text-muted">
            <%= link_to "Register", new_event_registration_path(@event), class: "btn btn-success" %>
            <%= link_to "Who's Registered?", event_registrations_path(@event), class: "btn btn-link" %>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
    <p>
        Copyright &copy; 2019 Dominic Davies
    </p>
</footer>

app/views/layouts/_jumbotron.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-4"><%= pluralize(@events.size, 'Event') %> Listed</h1>
    <p class="lead">This is a simple event listings app built with Ruby on Rails 5.2, Bootstrap 4.3.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Events', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "All Events", events_path, class: "nav-link" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <%= link_to "Add New Event", new_event_path, class: "btn btn-outline-success my-2 my-sm-0" %>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'shared/flash_msg' %>
    
      <%= yield %>


    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if @event.errors.any? %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <p class="lead"> Your form could not be saved. Please correct the following
        <%= pluralize(@event.errors.count, "error") %></p>
    <ul>
        <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
<% end %>

app/views/shared/_flash_msg.html.erb
<div class="container">
    <% if flash[:notice] %>
        <p class="alert alert-success" role="alert">
            <%= flash[:notice] %>
        </p>
    <% end %>
</div>